### ISSUE TITLE
File Upload Returns byte[] instead of InputFileChangeEventArgs

### ISSUE THREAD

**Issue by DaveHOnCode** [yagizhanNY/siemens-ix-blazor#7]
I'm trying to integrate the FileUpload Component into my application, but returns a byte array of the file content.

For using it as a replacement for the standard `InputFile`-Component, it would be appreciated, if it would return the `InputFileChangeEventArgs` instead, coz in this object a stream is returned that can be used to upload the file in a common manner aswell as the File Name.

Thanks in Advance

**Comment by yagizhanNY** [comment]
Yes, it's component returns file context as `byte[]`. It is not possible to send `File` object from javascript to c# via JS interops.

If needed, we can add file name to return object.

Do you have any suggestion?

**Comment by DaveHOnCode** [comment]
Maybe we could use the original `InputFile` Component as idea: [https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputFile.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputFile.cs)

So the component would be usable with existing implementations

**Comment by yagizhanNY** [comment]
But we must use siemens-ix components. 

I will check the return object of `InputFile` component. Maybe we can implement this return object to our component.

**Comment by yagizhanNY** [comment]
Please check the commit 52275ca. 

I created a custom file object named `IXFile`. This object contains `File Name`, `File Size`, `File Type` and `Base64 Data`. 

There is not a way to use `BrowseFile` object in JS interop. Because of that I created a new custom file object. 

Please reopen the issue if anything in your mind.
